apiVersion: v1
kind: Service
metadata:
  name: service-$BUILD_NUMBER
spec:
  type: NodePort
  selector:
    app: test-$BUILD_NUMBER
  ports:
  - protocol: TCP
    port: 808$BUILD_NUMBER
    targetPort: 808$BUILD_NUMBER
    nodePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-$BUILD_NUMBER
  labels:
    app: test-$BUILD_NUMBER
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-$BUILD_NUMBER
  template:
    metadata:
      labels:
        app: test-$BUILD_NUMBER
    spec:
      containers:
      - name: test-container
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 808$BUILD_NUMBER

