apiVersion: v1
kind: Service
metadata:
  name: $BUILD_NUMBER-service
spec:
  type: NodePort
  selector:
    app: $BUILD_NUMBER
  ports:
  - protocol: TCP
    port: 808+$BUILD_NUMBER
    targetPort: 808+$BUILD_NUMBER
    nodePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: $BUILD_NUMBER-deployment
  labels:
    app: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $BUILD_NUMBER
  template:
    metadata:
      labels:
        app: $BUILD_NUMBER
    spec:
      containers:
      - name: test-container
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 808+$BUILD_NUMBER

